name: Publish npm package

on:
  push:
    tags:
      - 'v*'  # Triggers when a version tag (e.g., v1.0.0) is pushed

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Change this if your project needs another version
          registry-url: 'https://registry.npmjs.org/'

      - name: Authenticate with npm
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build package (if needed)
        run: npm run build  # Change or remove if not needed

      - name: Publish to npm
        run: npm publish --access public
